name: validate tmdb
on:
  schedule:
    - cron: '0 8 * * 5'
      timezone: Asia/Hong_Kong
  workflow_dispatch:

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: 24

      - name: Checkout bangumi data
        uses: actions/checkout@v6
        with:
          ref: master
          path: ./bangumi-data

      - name: Checkout helper
        uses: actions/checkout@v6
        with:
          repository: kennyfong19931/helper
          ref: local
          path: ./helper

      - name: Run bdh to validate
        working-directory: ./helper
        run: |
          npm install
          npx bdh validate tmdb
          npx bdh validate tmdbBegin
